server:
  servlet:
  port: 9091
spring:
  application:
    name: SpringBootGraphQl
      #  Graph QL
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  main:
    banner-mode: console
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
    hikari:
      minimum-idle: 0
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: sbtraining-pool-cp
      max-lifetime: 200000
      connection-timeout: 30000
  jmx:
    enabled: false
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      release_mode: after_transaction
      agressive_release: true
      hibernate:
        id:
          new_generator_mappings: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl